"""Initial schema with stations, programs, schedules, and recordings


Revision ID: c12de8346d77
Revises: 
Create Date: 2025-10-31 09:06:01.597100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c12de8346d77'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programs',
    sa.Column('program_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('program_id')
    )
    op.create_index('ix_program_title', 'programs', ['title'], unique=False)
    op.create_index(op.f('ix_programs_title'), 'programs', ['title'], unique=False)
    op.create_table('stations',
    sa.Column('station_id', sa.String(length=32), nullable=False),
    sa.Column('callsign', sa.String(length=16), nullable=False),
    sa.Column('channel_number', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('station_id'),
    sa.UniqueConstraint('callsign', 'channel_number', name='uq_station_callsign_channel')
    )
    op.create_index(op.f('ix_stations_channel_number'), 'stations', ['channel_number'], unique=False)
    op.create_index(op.f('ix_stations_enabled'), 'stations', ['enabled'], unique=False)
    op.create_table('schedules',
    sa.Column('schedule_id', sa.String(length=64), nullable=False),
    sa.Column('program_id', sa.String(length=32), nullable=False),
    sa.Column('station_id', sa.String(length=32), nullable=False),
    sa.Column('air_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.program_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.station_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('schedule_id')
    )
    op.create_index('ix_schedule_station_time', 'schedules', ['station_id', 'air_datetime'], unique=False)
    op.create_index(op.f('ix_schedules_air_datetime'), 'schedules', ['air_datetime'], unique=False)
    op.create_index(op.f('ix_schedules_program_id'), 'schedules', ['program_id'], unique=False)
    op.create_index(op.f('ix_schedules_station_id'), 'schedules', ['station_id'], unique=False)
    op.create_table('recordings',
    sa.Column('recording_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('schedule_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', name='recordingstatus'), nullable=False),
    sa.Column('padding_start_seconds', sa.Integer(), nullable=False),
    sa.Column('padding_end_seconds', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('actual_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.schedule_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recording_id')
    )
    op.create_index('ix_recording_status_schedule', 'recordings', ['status', 'schedule_id'], unique=False)
    op.create_index(op.f('ix_recordings_schedule_id'), 'recordings', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_recordings_status'), 'recordings', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recordings_status'), table_name='recordings')
    op.drop_index(op.f('ix_recordings_schedule_id'), table_name='recordings')
    op.drop_index('ix_recording_status_schedule', table_name='recordings')
    op.drop_table('recordings')
    op.drop_index(op.f('ix_schedules_station_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_program_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_air_datetime'), table_name='schedules')
    op.drop_index('ix_schedule_station_time', table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_stations_enabled'), table_name='stations')
    op.drop_index(op.f('ix_stations_channel_number'), table_name='stations')
    op.drop_table('stations')
    op.drop_index(op.f('ix_programs_title'), table_name='programs')
    op.drop_index('ix_program_title', table_name='programs')
    op.drop_table('programs')
    # ### end Alembic commands ###
