"""Add Lineup and SyncStatus models, update Station and Schedule

Revision ID: ce90ff79a07a
Revises: c12de8346d77
Create Date: 2025-11-01 10:17:02.407299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce90ff79a07a'
down_revision: Union[str, Sequence[str], None] = 'c12de8346d77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lineups',
    sa.Column('lineup_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('transport', sa.String(length=32), nullable=True),
    sa.Column('location', sa.String(length=32), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('lineup_id')
    )
    op.create_table('sync_status',
    sa.Column('sync_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('lineups_updated', sa.Integer(), nullable=False),
    sa.Column('stations_updated', sa.Integer(), nullable=False),
    sa.Column('schedules_updated', sa.Integer(), nullable=False),
    sa.Column('programs_updated', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('sync_id')
    )
    op.create_index(op.f('ix_sync_status_started_at'), 'sync_status', ['started_at'], unique=False)
    op.add_column('schedules', sa.Column('md5_hash', sa.String(length=32), nullable=True))
    op.add_column('stations', sa.Column('lineup_id', sa.String(length=64), nullable=False))
    op.add_column('stations', sa.Column('affiliate', sa.String(length=32), nullable=True))
    op.add_column('stations', sa.Column('logo_url', sa.String(length=512), nullable=True))
    op.create_index(op.f('ix_stations_lineup_id'), 'stations', ['lineup_id'], unique=False)
    with op.batch_alter_table("stations") as batch_op:
        batch_op.create_foreign_key(constraint_name="fk_stations_lineupid_lineups", referent_table='lineups', local_cols=['lineup_id'], remote_cols=['lineup_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stations', type_='foreignkey')
    op.drop_index(op.f('ix_stations_lineup_id'), table_name='stations')
    op.drop_column('stations', 'logo_url')
    op.drop_column('stations', 'affiliate')
    op.drop_column('stations', 'lineup_id')
    op.drop_column('schedules', 'md5_hash')
    op.drop_index(op.f('ix_sync_status_started_at'), table_name='sync_status')
    op.drop_table('sync_status')
    op.drop_table('lineups')
    # ### end Alembic commands ###
