"""Add episode metadata to programs

Revision ID: fc82e4f344a3
Revises: ce90ff79a07a
Create Date: 2025-11-01 17:45:20.904279

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fc82e4f344a3"
down_revision: str | Sequence[str] | None = "ce90ff79a07a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("programs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("season", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("episode", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("episode_title", sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("programs", schema=None) as batch_op:
        batch_op.drop_column("episode_title")
        batch_op.drop_column("episode")
        batch_op.drop_column("season")

    # ### end Alembic commands ###
